# Generated by Django 4.2.20 on 2025-11-27 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0023_venta_descuento_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebajaDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_rebaja', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Rebajado')),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Anterior')),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Nuevo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones de la Rebaja')),
                ('fecha_rebaja', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebajas', to='facturacion.cuentaporcobrar')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rebaja de Deuda',
                'verbose_name_plural': 'Rebajas de Deuda',
                'db_table': 'rebajas_deuda',
                'ordering': ['-fecha_rebaja'],
            },
        ),
    ]
