# Generated by Django 4.2.20 on 2025-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_rebajadeuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebajadeuda',
            name='monto_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total Anterior'),
        ),
        migrations.AlterField(
            model_name='rebajadeuda',
            name='monto_nuevo',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total Nuevo'),
        ),
    ]
