# Generated by Django 4.2.20 on 2026-04-11 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0026_rebajadeuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Devuelta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Devuelto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.devolucion', verbose_name='Devolución')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devolución',
                'db_table': 'detalle_devolucion',
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('origen', models.CharField(choices=[('VENTA', 'Venta'), ('PAGO_CXC', 'Pago Cuenta por Cobrar'), ('DEVOLUCION', 'Devolución'), ('ANULACION', 'Anulación'), ('AJUSTE', 'Ajuste Manual')], max_length=20, verbose_name='Origen')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('REVERTIDO', 'Revertido')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha_operacion', models.DateTimeField(verbose_name='Fecha de Operación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Referencia')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='facturacion.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='facturacion.devolucion', verbose_name='Devolución')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='facturacion.venta', verbose_name='Factura/Venta')),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversos', to='facturacion.movimientofinanciero', verbose_name='Movimiento Original')),
                ('pago_cxc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='facturacion.pagocuentaporcobrar', verbose_name='Pago CxC')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'db_table': 'movimientos_financieros',
                'ordering': ['-fecha_operacion'],
                'indexes': [models.Index(fields=['tipo', 'origen', 'fecha_operacion'], name='movimientos_tipo_b5f76d_idx'), models.Index(fields=['fecha_operacion'], name='movimientos_fecha_o_aff014_idx'), models.Index(fields=['cliente', 'fecha_operacion'], name='movimientos_cliente_3302d5_idx'), models.Index(fields=['estado'], name='movimientos_estado_941267_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(verbose_name='N° Cuota')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Original')),
                ('monto_pendiente', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pendiente')),
                ('fecha_vencimiento', models.DateField(db_index=True, verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_pago_completo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago Completo')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='facturacion.cliente', verbose_name='Cliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='facturacion.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cuotas',
                'ordering': ['fecha_vencimiento'],
                'indexes': [models.Index(fields=['venta', 'estado'], name='cuotas_venta_i_73ea74_idx'), models.Index(fields=['cliente', 'estado'], name='cuotas_cliente_a24c71_idx'), models.Index(fields=['fecha_vencimiento'], name='cuotas_fecha_v_dddde4_idx')],
                'unique_together': {('venta', 'numero_cuota')},
            },
        ),
    ]
