# Generated by Django 4.2.20 on 2026-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_detalledevolucion_movimientofinanciero_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
