# Generated by Django 4.2.20 on 2026-04-25 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facturacion", "0030_clean_test_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagocuentaporcobrar",
            name="idempotency_key",
            field=models.UUIDField(
                blank=True,
                help_text="Clave generada por el cliente para evitar duplicados",
                null=True,
                unique=True,
                verbose_name="Clave de Idempotencia",
            ),
        ),
        migrations.CreateModel(
            name="IdempotencyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField(db_index=True, unique=True)),
                ("response_body", models.TextField()),
                ("status_code", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Idempotencia",
                "verbose_name_plural": "Logs de Idempotencia",
                "db_table": "idempotency_logs",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="idempotency_created_f3b168_idx"
                    )
                ],
            },
        ),
    ]
