# Generated by Django 4.2.20 on 2026-05-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0031_pagocuentaporcobrar_idempotency_key_idempotencylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='imei_serial',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
